name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      run: echo "Repository checked out successfully"

    - name: Setup Docker Buildx
      run: |
        echo "Setting up Docker Buildx"
        docker buildx create --use
        echo "Docker Buildx setup complete"
    
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
      run: echo "Docker layers cached"

    - name: Build the Docker image
      run: |
        echo "Starting Docker build"
        docker build . --file Dockerfile --tag jobet1995:$(date +%s)
        echo "Docker build completed"

    - name: List Docker images
      run: |
        echo "Listing Docker images"
        docker images
        echo "Docker images listed successfully"

    - name: Save Docker image to a tar file
      run: |
        echo "Saving Docker image to tar file"
        docker save jobet1995:$(date +%s) -o jobet1995.tar
        echo "Docker image saved successfully"

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v3
      with:
        name: jobet1995-docker-image
        path: jobet1995.tar
      run: echo "Docker image artifact uploaded successfully"

    - name: Clean up Docker images
      run: |
        echo "Cleaning up Docker images"
        docker rmi $(docker images -q)
        echo "Docker images cleaned up successfully"
