name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Echo checkout success
      run: echo "Repository checked out successfully"

    - name: Setup Docker Buildx
      run: |
        echo "Setting up Docker Buildx"
        docker buildx create --use
        echo "Docker Buildx setup complete"
    
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    
    - name: Echo cache success
      run: echo "Docker layers cached"

    - name: Build the Docker image
      run: |
        echo "Starting Docker build"
        IMAGE_TAG=jobet1995:$(date +%s)
        docker build . --file Dockerfile --tag $IMAGE_TAG
        echo "Docker build completed with tag $IMAGE_TAG"


    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v3
      with:
        name: jobet1995-docker-image
        path: jobet1995.tar

    - name: Echo artifact upload success
      run: echo "Docker image artifact uploaded successfully"

    - name: Clean up Docker images
      run: |
        echo "Cleaning up Docker images"
        docker rmi $(docker images -q)
        echo "Docker images cleaned up successfully"
